version: '3'
services:
  telegram_bot:
    container_name: telegram_bot
    build:
      .
    volumes:
      - ./temp:/app/temp
      - ./sessions:/app/sessions
      - ./configuration.ini:/app/configuration.ini
    restart: always